### ISSUE TITLE
Training speed decreases every 500 iteration

### ISSUE THREAD

**Issue by ZidongLiu** [ZidongLiu/FedDisco#18]
![image](https://github.com/user-attachments/assets/d02490f3-1d0c-4323-b579-27c1d8b06e55)

on commit https://github.com/ZidongLiu/FedDisco/commit/838f2b37df55e37283232238e7cf47ad3f573c48
following code runs slower and slower

`python cezo_fl_main.py --dataset=sst2 --iterations=10000 --train-batch-size=8 --test-batch-size=200 --eval-iterations=50 --num-clients=3 --num-sample-clients=2 --local-update-steps=1 --num-pert=10 --lr=1e-6 --mu=1e-3 --grad-estimate-method=rge-forward`

**Comment by BichengYing** [comment]
Some investigation suggestions:
- Check if we can observe a similar slowdown with much smaller dataset and/or modify the train-batch-size
- If we suspect it is related to dataset loader, we can try to use a fake data (like a fixed random tensor input) then execute the algorithm 
- If we suspect it is related to memory in server, we can print out the memory consumption of each class member every 100 iterations.

**Comment by ZidongLiu** [comment]
Close this issue because it's not a bug.
issue was caused by perturbation adjustment. 
https://github.com/ZidongLiu/FedDisco/blob/main/cezo_fl_main.py#L195-L204
